export const STRING_CONSTANTS = {
  MSG: 'Message',
  SPLASH_CONSTANTS_ROOTED_MSG_IOS:
    'Device is rooted device you cannot use this app. Please remove app from \ndevice.',
  SPLASH_CONSTANTS_ROOTED_MSG_ANDROID:
    'Device is rooted device you cannot use this app. Please remove app from device.',
  SPLASH_CONSTANTS_IS_VALID_IOS:
    'Your application is not valid. Please install from App store.',
  SPLASH_CONSTANTS_IS_VALID_ANDROID:
    'Your application is not valid. Please install from Google playstore.',
  PLATFORM_IOS: 'ios',
  MYAADHAAR: 'Myadhar',
  IS_REGISTRED: 'isRegistered',
  YES: 'yes',
  SCREEN_NAME: 'SCREEN_NAME',
  CONSENT_AGREE: 'consent_agree',
  ADD_PROFILE: 'AddProfile',
  TRUE: 'true',
  FALSE: 'false',
  MAIN_APP: 'MainApp',
  GET_STARTED: 'GetStarted',
  GET_STARTED_MAIN: 'GetStartedMain',
  FAILURE: 'Failure',
  SSUP_ID: 'id',
  SSUP_NAME: 'name',
  SSUP_NAVIGATE_NAME: 'AadharSsupNameUpdateScreen',
  SSUP_DOB: 'dob',
  SSUP_NAVIGATE_DOB: 'AadhaarSsupDobScreen',
  SSUP_GENDER: 'gender',
  SSUP_NAVIGATE_GENDER: 'AadhaarSsupGenderScreen',
  SSUP_ADDRESS: 'address',
  SSUP_NAVIGATE_ADDRESS: 'AadhaarSsupAddressEditScreen',
  // SSUP_NAVIGATE_ADDRESS: 'AadhharSsupAddressScreen',
  SSUP_MOBILE: 'mobileNumber',
  SSUP_NAVIGATE_MOBILE: 'AadhaarSsupMobileScreen',
  SSUP_EMAIL_ID: 'emailID',
  SSUP_NAVIGATE_EMAIL_ID: 'AadhaarSsupEmailScreen',
  SSUP_LANGUAGE: 'language',
  SSUP_NAVIGATE_LANGUAGE: 'AadhaarSsupLanguageScreen',
  CONTAIN: 'contain',
  HANDLED: 'handled',
  SCROLLVIEW: 'scrollView',
  TEN_PERCENT: '10%',
  SSUP_NAVIGATE_DETAILS: 'AadhaarSsupDetailsScreen',
  OTP_N_FACE_AUTH_SCREEN: 'OtpNfaceAuthScreen',
  MAADHAR_AADHAAR_SSUP: 'MAADHAR_AADHAAR_SSUP',
  SSUP_NAVIGATE_VERIFY: 'AadhaarSsupVerifyOtpScreen',

  SELECT: 'Select document from the list',
  SELECT_DOC_MSG: 'select a document',
  UPLOAD_DOC_MSG: 'upload a document',
  DATE_FORMAT: 'DD/MM/YYYY',
  APPLICATION_PDF: 'application/pdf',
  IMAGE_JPEG: 'image/jpeg',
  IMAGE_JPG: 'image/jpg',
  IMAGE_PNG: 'image/png',
  JPG: 'jpg',
  PDF: 'pdf',
  JPEG: 'jpeg',
  PNG: 'png',
  FILE_SIZE_MSG: 'File size greater than 2 MB',
  FILE_NOT_SUPPORT: 'File format not supported',
  BASE64: 'base64',
  DOB_EXISTS_MSG:
    'Dear resident the date of birth you have entered already exists in your Aadhaar. Please enter correct/relevant data for update',
  SELECT_DAT_OF_BIRTH: 'select date of birth',
  DATE: 'date',
  DOC: 'doc',
  DOC_LIST: 'docList',
  SSUP_DOC: 'document',
  SSUP_UPLOAD: 'upload',
  SSUP_VILLAGE: 'village',
  SSUP_POSTOFFICE: 'postoffice',
  SSUP_DISTRICT: 'district',
  SSUP_STATE: 'state',
  SSUP_CAREOF: 'careof',
  SSUP_HOUSE: 'house',
  SSUP_AREA: 'area',
  SSUP_STREET: 'street',
  SSUP_PINCODE: 'pincode',
  SSUP_SELECT_PINCODE_MSG: 'select a pincode',
  SSUP_SELECT_VILLAGE_MSG: 'select a village',
  SSUP_SELECT_PO_MSG: 'select a postOffice',
  SSUP_SELECT_DISTRICT_MSG: 'select a district',
  SSUP_SELECT_STATE_MSG: 'select a state',
  SSUP_ALLOW_UIDAI_TRANSLITERATION_MSG: 'allow UIDAI for transliteration',
  SSUP_AADHAAR: 'aadhaar',
  SSUP_TRUE: 'true',
  SSUP_FALSE: 'false',
  SSUP_CAPTCHA: 'captcha',
  SSUP_IN_PROGRESS: 'IN_PROGRESS',
  SSUP_CANCELLED: 'CANCELLED',
  SSUP_CANCELED: 'CANCELED',
  SSUP_CC_CANCELLED: 'Cancelled',
  SSUP_C_REJECTED: 'REJECTED',
  SSUP_CC_REJECTED: 'Rejected',
  SSUP_S_REJECTED: 'rejected',
  SSUP_VALIDATION_PENDING: 'VALIDATION_PENDING',
  SSUP_C_SUCCESS: 'SUCCESS',
  SSUP_CC_SUCCESS: 'Success',
  SSUP_S_SUCCESS: 'success',
  SSUP_C_PENDING: 'PENDING',
  SSUP_CC_PENDING: 'Pending',
  SSUP_S_PENDING: 'pending',
  SSUP_CC_FAILURE: 'Failure',

  PVC_Completed: 'Completed',
  PVC_Inprocess: 'InProcess',
  PVC_Onhold: 'OnHold',
  SSUP_IN_PROGRESS_STATUS: 'In Progress',
  SSUP_VALIDATION_PENDING_STATUS: 'Validation Pending',
  SSUP_DOR: 'Date of Payment',
  SSUP_DEMOGRAPHICS_UPDATE: 'DEMOGRAPHICS_UPDATE',
  SSUP_CANCEL_REQUEST: 'Cancel Request',
  //SSUP_AADHAAR_REPRINT: 'Aadhaar Reprint',
  SSUP_AADHAAR_REPRINT: 'PVC Card Requests',
  SSUP_AADHAAR_UPDATE_STATUS: 'Aadhaar Update Status',
  SSUP_REQUEST_ADDRESS_VALIDATION_LETTER: 'Request Address Validation Letter',
  SSUP_CONGRATS: 'Congratulation!',
  SSUP_CANCELLED_REQ_MSG: 'Your request has been cancelled.',
  SSUP_REJECTED_REQ_MSG: 'Your request has been rejected.',
  SSUP_SUCCESS_REQ_MSG: 'Your request has been successful!',
  SSUP_DATA_MISMATCH_REQ_MSG: 'Data mismatch in document and update request.',
  SSUP_URN: 'URN',
  SSUP_STATUS: 'Status',
  SSUP_OAR_ACK_MSG: 'Acknowledgement reciept for Aadhaar reprint order',
  SSUP_OAR_PAYMENT_DATE: 'Payment Date',
  SSUP_OAR_PAYMENT_TIME: 'Time',
  SSUP_SRN: 'SRN',
  SSUP_RECIEPT_NUMBER: 'Receipt Number',
  SSUP_TRANSACTION_ID: 'Transaction ID',
  SSUP_AMOUNT: 'Amount',
  SSUP_AADHAAR_NUMBER: 'Aadhaar Number',
  SSUP_TRANSACTION_STATUS: 'Transaction Status',
  SSUP_NOTE: 'Note',
  SSUP_REJECTED_MSG:
    'Your request has been rejected due to data mismatch in document and update request.',
  SSUP_REFUND_MSG: 'Your transaction amount will be refund with in 7 days.',
  SSUP_ADDRESS_VALIDATION_LETTER: 'ADDRESS_VALIDATION_LETTER',
  SSUP_ORDER_AADHAAR_REPRINT: 'ORDER_AADHAAR_REPRINT',

  SSUP_SUCCESS_MSG: 'Congratulation! Your Aadhaar is Updated!',
  SSUP_VERIFICATION_PENDING_MSG: 'Your Request pending for verification.',
  SSUP_REJECTED_MSG: 'Your Request for Update has been rejected.',
  SSUP_INPROGRESS_MSG: 'Your Request for Update in process.',
  SSUP_CANCELLED_MSG: 'Your Request for update is cancelled.',
  SSUP_FAILURE_MSG: 'Your Request for update failed.',

  SSUP_PAYMENT_AMOUNT: 'Amount',
  SSUP_PAYMENT_EMAIL: 'Email',
  SSUP_PAYMENT_UID: 'UID',
  SSUP_MAX_DOB_ERROR:
    'You have exhausted DOB update options or your DOB has been verified at the time of enrolment.',
  SSUP_MAX_NAME_ERROR: 'You have exhausted Name update options.',
  SSUP_MAX_ADDRESS_ERROR: 'You have exhausted Address update options.',
  SSUP_MAX_GENDER_ERROR: 'You have exhausted Gender update options.',
  SSUP_MAX_LANG_ERROR: 'You have exhausted Language update options.',
  SSUP_DOB_ERROR:
    'You have already requested for Date of birth update.Your request is under process.',
  SSUP_NAME_ERROR:
    'You have already requested for Name update.Your request is under process.',
  SSUP_ADDRESS_ERROR:
    'You have already requested for Address update.Your request is under process.',
  SSUP_GENDER_ERROR:
    'You have already requested for Gender update.Your request is under process.',
  SSUP_LANG_ERROR:
    'You have already requested for Language update.Your request is under process.',

  SSUP_CHARGEABLE_MESSAGE: 'You will be charged Rs',
  SSUP_CHARGEABLE_TRUN_MESSAGE: 'for the update transaction.',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_PENDING_STR: 'Payment pending',
  PAYMENT_FAIL: 'PAYMENT_FAIL',
  PAYMENT_FAIL_STR: 'Payment Failed',
  REQUEST_FOUND_STR: 'Request(s) found in record',
  MORE_ITEMS: 'more items',

  qrCodeSecureVerNA: 'V0',
  qrcodeSecureVerEmail: 'V1',
  qrCodeSecureVerMob: 'V2',
  qrCodeSecureVerBOth: 'V3',
  qrCodeSecureEmailMObileVerBOth: 'V4',
  qrCodeSecureAddressValidity: 'V5',

  qrCodeVerNA: '0',
  qrcodeVerEmail: '1',
  qrCodeVerMob: '2',
  qrCodeVerBOth: '3',

  submit: 'Submit',
};
